### PR TITLE
Initial Dockerfile. Updated README

### PR DESCRIPTION
**Pull request by jasonmeverett**
This update contains a working Dockerfile for installing ASSET into a Docker image. Tested on Ubuntu 20.04.

### CODE REVIEW

**Comment by jbpezent** [comment]
Jason, I'm gunna merge this in and then move the Docker install section on the front page to the install section in the documentation.

**Comment by jasonmeverett** [comment]
> 

Sounds good. Sorry for making more work for you!

**Comment by jbpezent** [comment]
No problem. It has been moved into Install.rst in the docs folder. Add any extra you were going to sayabout vscode extensions there and then I will deploy to gh-pages.

**Comment by jbpezent** [comment]
Also, we probably should make a docker account specifically for ASSET and host the image there. Not super important right now, but we will discuss that soon.

**Pull request merged**
